apiVersion: v1
kind: Service
metadata:
  name: knowledge-service
  namespace: youtube
spec:
  selector:
    app: knowledge-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP
